### ISSUE TITLE
[AIFlow] Periodic workflow doesn't run

### ISSUE THREAD

**Issue by Sxnan** [flink-extended/ai-flow#52]
### Describe the bug
Change the `simple_workflow.yaml` to the following so that it should run every minutes:
```
periodic_config:
  cron: '0 * * * * * *'
task_1:
  job_type: bash
task_2:
  job_type: bash
```

After submitting, we can see that the dag run is created every minute, but its tasks are not running.

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/12155662/139235288-390161a8-b295-4a42-9936-9eb0a8e785b8.png">
